//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTrackerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssignExam_ToAgent
    {
        public int AssignID { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> testId { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<int> Controller { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Marks { get; set; }
        public Nullable<System.DateTime> TestCompleteDate { get; set; }
    }
}
