//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTrackerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuiz
    {
        public int QuizId { get; set; }
        public string QuizName { get; set; }
        public int TotalQuestions { get; set; }
        public int TimeAllocated { get; set; }
        public int PassingScore { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int CatID { get; set; }
    
        public virtual tblTestCategory tblTestCategory { get; set; }
    }
}
