//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTrackerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTestSetting
    {
        public int TestId { get; set; }
        public int TimeLimit { get; set; }
        public int NumberOfQuestions { get; set; }
        public Nullable<int> TestCatID { get; set; }
        public string TestSettingName { get; set; }
        public Nullable<int> PassingPer { get; set; }
    }
}
