//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTrackerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserAnswers_Latest
    {
        public int id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> QuizID { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public Nullable<int> isCorrect { get; set; }
        public int SerialNumber { get; set; }
        public Nullable<int> AssignID { get; set; }
    }
}
